package Acme::CPANLists::Import::Caching;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://cpan.robm.fastmail.fm/cache_perf.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Cache::FastMmap"}],summary=>"Comparison of different Perl caching modules (2002-2005)"});

1;
# ABSTRACT: Comparison of different Perl caching modules (2002-2005)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://cpan.robm.fastmail.fm/cache_perf.html> (retrieved on 2016-02-21). For the full article, visit the URL.

