package Acme::CPANLists::Import::CombinationsAndPermutations;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/dana_jacobsen/2015/02/short-survey-of-modules-for-combinations-and-permutations.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Algorithm::Combinatorics"},{module=>"Algorithm::FastPermute"},{module=>"Algorithm::Loops"},{module=>"Algorithm::Permute"},{module=>"Iterator::Misc"},{module=>"List::Permutor"},{module=>"Math::Combinatorics"},{module=>"Math::Counting"},{module=>"Math::Disarrange::List"},{module=>"Math::GSL::Combination"},{module=>"Math::GSL::Permutation"},{module=>"Math::Pari"},{module=>"Math::Permute::Array"},{module=>"Math::Permute::List"},{module=>"ntheory"}],summary=>"Short survey of modules for combinations and permutations (2015)"});

1;
# ABSTRACT: Short survey of modules for combinations and permutations (2015)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://blogs.perl.org/users/dana_jacobsen/2015/02/short-survey-of-modules-for-combinations-and-permutations.html> (retrieved on 2016-02-21). For the full article, visit the URL.

