package Acme::CPANLists::Import::DatesPart2;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/buddy_burden/2015/10/a-date-with-cpan-part-2-target-first-aim-afterwards.html] (retrieved on 2016-07-19). For the full article, visit the URL.",entries=>[{module=>"Date::Parse"},{module=>"Date::Piece"},{module=>"Time::Moment"},{module=>"Time::ParseDate"},{module=>"Time::Piece"}],summary=>"CPAN modules for processing dates - Part 2"});

1;
# ABSTRACT: CPAN modules for processing dates - Part 2

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://blogs.perl.org/users/buddy_burden/2015/10/a-date-with-cpan-part-2-target-first-aim-afterwards.html> (retrieved on 2016-07-19). For the full article, visit the URL.

