package Acme::CPANLists::Import::JSONDecoders;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://perlmaven.com/comparing-the-speed-of-json-decoders] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Benchmark"},{module=>"Cpanel::JSON::XS"},{module=>"Cpanel::JSON::XS::decode_json"},{module=>"JSON"},{module=>"JSON::MaybeXS"},{module=>"JSON::PP"},{module=>"JSON::PP::decode_json"},{module=>"JSON::XS"},{module=>"JSON::XS::decode_json"},{module=>"JSON::decode_json"},{module=>"JSON::encode_json"},{module=>"Text::CSV"},{module=>"Text::CSV_XS"}],summary=>"Comparing the speed of JSON decoders (2015)"});

1;
# ABSTRACT: Comparing the speed of JSON decoders (2015)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://perlmaven.com/comparing-the-speed-of-json-decoders> (retrieved on 2016-02-21). For the full article, visit the URL.

