package Acme::CPANLists::Import::ORM;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://www.perlmonks.org/?node_id=700283] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Alzabo"},{module=>"Catalyst"},{module=>"Class::DBI"},{module=>"DBI"},{module=>"DBIx::Class"},{module=>"DateTime"},{module=>"Fey"},{module=>"Ima::DBI"},{module=>"Rose"},{module=>"Rose::DB"},{module=>"Rose::DB::Object"},{module=>"SQL::Abstract"}],summary=>"Perl ORM comparison (Class::DBI vs DBIx::Class vs Rose::DB::Object) (2008)"});

1;
# ABSTRACT: Perl ORM comparison (Class::DBI vs DBIx::Class vs Rose::DB::Object) (2008)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://www.perlmonks.org/?node_id=700283> (retrieved on 2016-02-21). For the full article, visit the URL.

