package Acme::CPANLists::Import::RomanNumbers;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://datetime.mongueurs.net/divers/nombres-romains/Roman_Numbers.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Acme::MetaSyntactic::roman"},{module=>"Acme::Roman"},{module=>"Convert::Number::Roman"},{module=>"Language::Befunge::lib::ROMA"},{module=>"Lingua::Romana::Perligata"},{module=>"Math::Roman"},{module=>"Math::Roman::roman"},{module=>"Math::Roman::tokens"},{module=>"Roman"},{module=>"Roman::Roman"},{module=>"Roman::Unicode"},{module=>"Text::Roman"},{module=>"YAPC::Europe"}],summary=>"Roman Numbers (2009)"});

1;
# ABSTRACT: Roman Numbers (2009)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://datetime.mongueurs.net/divers/nombres-romains/Roman_Numbers.html> (retrieved on 2016-02-21). For the full article, visit the URL.

