package Acme::CPANLists::Import::TemplatingSystem;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [https://perl.apache.org/docs/tutorials/tmpl/comparison/comparison.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Apache::ASP"},{module=>"Apache::AxKit"},{module=>"Apache::DB"},{module=>"Apache::Filter"},{module=>"Apache::Include"},{module=>"Apache::PageKit"},{module=>"Apache::Registry"},{module=>"Apache::SSI"},{module=>"Apache::Session"},{module=>"Apache::Template"},{module=>"Apache::ePerl"},{module=>"CGI::Application"},{module=>"CGI::FastTemplate"},{module=>"Devel::DProf"},{module=>"HTML::Embperl"},{module=>"HTML::FillInForm"},{module=>"HTML::Template"},{module=>"HTML::Tree"},{module=>"IPC::SharedCache"},{module=>"Template::TAL"},{module=>"Text::Template"},{module=>"Text::Template::fill_in_file"},{module=>"Time::HiRes"},{module=>"XML::LibXML"},{module=>"XML::XSLT"}],summary=>"Choosing a templating system (2014)"});

1;
# ABSTRACT: Choosing a templating system (2014)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<https://perl.apache.org/docs/tutorials/tmpl/comparison/comparison.html> (retrieved on 2016-02-21). For the full article, visit the URL.

