package Acme::CPANLists::Import::TemplateRoundup;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://www.illusori.co.uk/projects/Template-Roundup/] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"App::podweaver"},{module=>"Cache::CacheFactory"},{module=>"Cache::FastMemoryCache"},{module=>"Cache::Ref::FIFO"},{module=>"HTML::Macro"},{module=>"HTML::Mason"},{module=>"Parse::Template"},{module=>"Perl::Critic"},{module=>"Solution"},{module=>"Template::Benchmark"},{module=>"Template::Sandbox"},{module=>"Text::Clevery"},{module=>"Text::Matrix"},{module=>"Text::Templet"},{module=>"Text::Xslate"}],summary=>"Perl Template Roundup (2010)"});

1;
# ABSTRACT: Perl Template Roundup (2010)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://www.illusori.co.uk/projects/Template-Roundup/> (retrieved on 2016-02-21). For the full article, visit the URL.

