package Acme::CPANLists::Import::ThreadPoolForBossWorkerModel;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in the article [http://blogs.perl.org/users/kal/2012/09/thread-pool-for-a-bossworker-model.html] (retrieved on 2016-02-21). For the full article, visit the URL.",entries=>[{module=>"Beanstalk::Client"},{module=>"GraphViz2::Marpa"},{module=>"POE::Component::JobQueue"},{module=>"Parallel::Workers"},{module=>"Thread::Apartment"},{module=>"Thread::Pool"},{module=>"Thread::Queue"},{module=>"Thread::Semaphore"},{module=>"Thread::Workers"},{module=>"threads::shared"}],summary=>"Thread pool for a boss/worker model (2012)"});

1;
# ABSTRACT: Thread pool for a boss/worker model (2012)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in the article L<http://blogs.perl.org/users/kal/2012/09/thread-pool-for-a-bossworker-model.html> (retrieved on 2016-02-21). For the full article, visit the URL.

